import { readFileSync } from "node:fs"

import { describe, expect, it } from "vitest"

describe("active program queue header", () => {
  it("selects the authorized AEH outcome while preserving standing owner outcome delivery", () => {
    const queue = readFileSync("docs/governance/active-program-queue.md", "utf8")
    const goalRegistry = readFileSync("docs/governance/goal-registry.md", "utf8")
    const loopRegistry = readFileSync("docs/governance/loop-registry.md", "utf8")
    const program = readFileSync("docs/governance/owner-outcome-delivery-program.md", "utf8")

    expect(queue).toContain("Active program: `PROGRAM-WILLIAMOS-AI-EVALOPS-HARNESS-001`")
    expect(queue).toContain("Goal: `GOAL-WILLIAMOS-DURABLE-AI-EXECUTION-001`")
    expect(queue).toContain("Loop: `LOOP-WILLIAMOS-DURABLE-AI-EXECUTION-001`")
    expect(queue).toContain("Risk ceiling: `R1 ACTIVE`")
    expect(queue).toContain("WO-OWNER-OUTCOME-009")
    expect(queue).toContain("WO-OWNER-OUTCOME-009` is `READY")
    expect(queue).toContain("PROGRAM-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001` remains active")
    expect(goalRegistry).toContain("GOAL-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001")
    expect(goalRegistry).toContain("PROGRAM-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001")
    expect(goalRegistry).toContain("LOOP-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001")
    expect(goalRegistry).toContain("### `GOAL-WOE-DETAIL-SURFACES-001 - Work Order Engine Detail Surfaces`")
    expect(goalRegistry).toContain("Status: `complete / closed evidence`")
    expect(loopRegistry).toContain("LOOP-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001")
    expect(loopRegistry).toContain("GOAL-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001")
    expect(loopRegistry).toContain("WO-OWNER-OUTCOME-009")
    expect(loopRegistry).toContain("### `LOOP-WOE-DETAIL-SURFACES-001`")
    expect(loopRegistry).toContain("Status: `complete / closed evidence`")
    expect(queue).toContain("PROGRAM-WILLIAMOS-WOE-DETAIL-SURFACES-001")
    expect(queue).toContain("WO-WILLIAMOS-WOE-DETAIL-SURFACES-003")
    expect(queue).toContain("Property Workbench, TerraPilot, county work, PACS access")
    expect(queue).toContain("remain blocked")
    expect(queue).not.toContain("Active program: `PROGRAM-PROPERTY-WORKBENCH-001")
    expect(queue).not.toContain("Active program: `PROGRAM-TERRAPILOT-LIVE-001")
    expect(queue).not.toContain("Active program: `PROGRAM-COUNTY-RUNTIME-READINESS-001")
    expect(queue).not.toContain("Active program: `PROGRAM-WILLIAMOS-OWNER-OUTCOME-DELIVERY-001`")
    expect(queue).not.toContain("Goal: `GOAL-WOS-MULTI-AGENT-OPERATOR-001`")
    expect(queue).not.toContain("Loop: `LOOP-WOS-MULTI-AGENT-OPERATOR-001`")
    expect(queue).not.toContain("Risk ceiling: `R3` for control-plane implementation")
    expect(program).toContain("Status: `READY / STANDING_AWAITING_OUTCOME`")
    expect(program).toContain("NO_ACTIVE_PROGRAM` is forbidden")
  })
})
