import assert from'node:assert/strict';import test from'node:test';import{evaluateGpuAdmission,sealGpuAdmissionInput}from'../lib/execution-control/gpu-admission.mjs'
const sha=c=>'sha256:'+c.repeat(64),id=n=>`${n}0000000-0000-4000-8000-000000000001`,binding={jobId:id(1),claimId:id(2),attemptId:id(3),leaseId:id(4),effectDomain:'gpu:sim',idempotencyKey:'one',workerId:id(5),instanceId:id(6),bootId:id(7),fencingToken:'1',renewalSequence:'0',authorityDigest:sha('1'),capabilityDigest:sha('2'),inputDigest:sha('3'),baseDigest:sha('4'),policyDigest:sha('5'),requestedOutputDigest:sha('6'),configDigest:sha('7'),imageDigest:sha('8'),modelDigest:sha('a')}
const unbound=sealGpuAdmissionInput({schemaVersion:'aeh.gpu-admission.input.v1',evaluationId:id(8),evaluatedAt:'2026-08-11T12:00:00.000Z',inputDigest:sha('0'),binding,model:{modelDigest:sha('a'),runtimeKind:'ollama',runtimeDigest:sha('b'),contextTokens:100,requestedOutputTokens:20,concurrency:1},measurement:{measurementDigest:sha('0'),snapshotSourceDigest:sha('d'),modelDigest:sha('a'),runtimeDigest:sha('b'),weightsBytes:4000,runtimeOverheadBytes:1000,kvFormulaVersion:'kv.v1',kvSourceDigest:sha('c'),kvBytesPerToken:2,observedAt:'2026-08-11T11:59:30.000Z',ttlSeconds:60,confidence:'observed',gpuTotalVramBytes:10000,freeVramBytes:6240,freeRamBytes:5000,temperatureMilliC:60000,queueDepth:0,residentModels:[sha('a')]},policy:{policyDigest:sha('0'),reserveVramBytes:1000,maxTemperatureMilliC:80000,maxQueueDepth:1,allowedModelDigests:[sha('a')],allowedRuntimeDigests:[sha('b')]}});unbound.binding.policyDigest=unbound.policy.policyDigest;const base=sealGpuAdmissionInput(unbound)
const ev=x=>evaluateGpuAdmission(x),copy=()=>structuredClone(base),reseal=x=>{let v=sealGpuAdmissionInput(x);v.binding.policyDigest=v.policy.policyDigest;return sealGpuAdmissionInput(v)}
test('closed WO021-bound envelope admits deterministically with canonical digest',()=>{const a=ev(copy()),b=ev(copy());assert.deepEqual(a,b);assert.equal(a.status,'ADMIT_SIMULATION',JSON.stringify(a));assert.equal(a.calculated.requiredVramBytes,6240);assert.match(a.decisionDigest,/^sha256:[a-f0-9]{64}$/);assert.equal(a.dispatchAllowed,false)})
test('VRAM plus/minus one and monotonic reserve/context properties',()=>{for(const delta of[-1,0,1]){const x=copy();x.measurement.freeVramBytes=6240+delta;assert.equal(ev(reseal(x)).status,delta<0?'REJECT':'ADMIT_SIMULATION')}for(const field of['reserveVramBytes']){const lo=copy(),hi=copy();hi.policy[field]++;assert.ok(ev(lo).calculated.requiredVramBytes<ev(reseal(hi)).calculated.requiredVramBytes)}const c=copy();c.model.contextTokens++;assert.ok(ev(reseal(c)).calculated.requiredVramBytes>ev(copy()).calculated.requiredVramBytes)})
test('valid capacity failures are REJECT with sorted stable reasons',()=>{const x=copy();x.measurement.freeVramBytes=1;x.measurement.freeRamBytes=1;x.measurement.temperatureMilliC=80000;x.measurement.queueDepth=2;x.measurement.residentModels=[];const r=ev(reseal(x));assert.equal(r.status,'REJECT');assert.deepEqual(r.reasonCodes,[...r.reasonCodes].sort());assert.ok(r.reasonCodes.includes('VRAM_INSUFFICIENT'));assert.ok(r.reasonCodes.includes('RAM_INSUFFICIENT'))})
test('stale future mismatch concurrency allowlist and closed fields fail closed',()=>{const cases=[];let x=copy();x.measurement.observedAt='2026-08-11T11:59:00.000Z';cases.push(reseal(x));x=copy();x.measurement.observedAt='2026-08-11T12:00:01.000Z';cases.push(reseal(x));x=copy();x.measurement.runtimeDigest=sha('e');cases.push(reseal(x));x=copy();x.model.concurrency=2;cases.push(reseal(x));x=copy();x.extra=true;cases.push(x);for(const v of cases)assert.equal(ev(v).status,'INPUT_REJECTED')})
test('safe integer overflow, zero, undefined, NaN and conflict are INPUT_REJECTED',()=>{for(const bad of[Number.MAX_SAFE_INTEGER,0,undefined,NaN]){const x=copy();x.measurement.weightsBytes=bad;assert.equal(ev(x).status,'INPUT_REJECTED')}let x=copy();x.measurement.freeVramBytes=x.measurement.gpuTotalVramBytes+1;assert.equal(ev(reseal(x)).status,'INPUT_REJECTED');x=copy();x.measurement.kvBytesPerToken=Number.MAX_SAFE_INTEGER;assert.equal(ev(reseal(x)).status,'INPUT_REJECTED')})
test('same immutable snapshot estimates concurrently without granting a reservation',async()=>{const [a,b]=await Promise.all([Promise.resolve().then(()=>ev(copy())),Promise.resolve().then(()=>ev(copy()))]);for(const r of[a,b]){assert.equal(r.status,'ADMIT_SIMULATION');assert.equal(r.calculated.reservationCreated,false);assert.equal(r.dispatchAllowed,false)}assert.deepEqual(a,b)})
test('historical Hermes placement evidence is insufficient for admission',()=>{const historical={schema_version:'0.2-pinned-placement-recommendation',recommendation_only:true,recommendation:{node_id:'hermes-node'},evidence_snapshot:[]};const r=ev(historical);assert.equal(r.status,'INPUT_REJECTED');assert.equal(r.dispatchAllowed,false);assert.equal(r.executionAuthorized,false)})
test('every material binding measurement and policy mutation is integrity-bound',()=>{const original=ev(copy()),groups=['binding','measurement','policy'];for(const group of groups)for(const field of Object.keys(base[group]).filter(x=>x!=='measurementDigest'&&x!=='policyDigest')){const x=copy(),v=x[group][field];if(typeof v==='number')x[group][field]=v+1;else if(Array.isArray(v))x[group][field]=[...v,sha('f')];else if(typeof v==='string'&&/^sha256:/.test(v))x[group][field]=sha('e');else if(typeof v==='string'&&/^\d{4}-/.test(v))x[group][field]='2026-08-11T11:59:31.000Z';else if(typeof v==='string'&&/^[a-f0-9-]{36}$/i.test(v))x[group][field]=v.slice(0,-1)+'2';else if(field==='confidence')x[group][field]='proven';else x[group][field]=v+'x';assert.equal(ev(x).status,'INPUT_REJECTED',`${group}.${field} stale digest`);const refreshed=ev(group==='binding'?sealGpuAdmissionInput(x):reseal(x));assert.notEqual(refreshed.decisionDigest,original.decisionDigest,`${group}.${field} receipt`)}})
