import fs from "node:fs"
import path from "node:path"

import { describe, expect, it } from "vitest"

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8")

const shell = () => read("components/workspace-shell/workspace-shell.tsx")
const spatialCss = () => read("components/workspace-shell/experience-spatial.module.css")

describe("WilliamOS Experience V2 shell", () => {
  it("preserves a spatial workspace with independently durable work windows", () => {
    const source = shell()
    expect(source).toContain("WindowFrame")
    expect(source).toContain('id="editor"')
    expect(source).toContain('id="running-app"')
    expect(source).toContain('(["tests", "diff", "terminal"] as const)')
    expect(source).toContain("windowLayer")
    expect(source).toContain("dockButton")
    expect(source).not.toContain("experience.sourceRegion")
    expect(source).not.toContain("experience.previewRegion")
  })

  it("keeps The Line transient and grounds object actions in the selected source", () => {
    const source = shell()
    expect(source.match(/<input\b/g)).toHaveLength(1)
    expect(source).not.toContain("<textarea")
    expect(source).toContain("lineOpen ? (")
    expect(source).toContain('aria-label={lineMode === "change" ? changeIntent === "improve-diff" ? "Improve current change" : "Change"')
    expect(source).toContain('["Ask", "Change", "Delegate", fileReviewUnavailableReason ? "Review unavailable" : "Review"] as const')
    expect(source).toContain('["Inspect", "Debug", previewExplainUnavailableReason ? "Explain unavailable" : "Explain", "Delegate"] as const')
    expect(source).toContain('if (selectedKind === "preview" && action === "Debug")')
    expect(source).toContain("setAutomaticPreviewDebugPending(true)")
    expect(source).toContain("agentSessions.activeSessionIds.length !== 0")
    expect(source).toContain('turn.provider === "Claude" && turn.role === "Preview debugger" && turn.sessionId === null')
    expect(source).toContain("agentSessions.stop(pendingPreviewTurns[0].id)")
    expect(source).toContain("void submitLine(null, PREVIEW_DEBUG_PROMPT)")
    expect(source).toContain("await agentSessions.runPreviewDiagnostic(turn)")
    expect(source).toContain('aria-label="Stop Preview debug"')
    expect(source).toContain('[diffReviewUnavailableReason ? "Review unavailable" : "Review", "Improve", diffChallengeUnavailableReason ? "Challenge unavailable" : "Challenge", "Merge unavailable"] as const')
    expect(source).toContain('action === "Merge unavailable"')
    expect(source).toContain('Current Changes actions are read-only; merge is unavailable here.')
    expect(source).toContain('selectedKind === "diff" && action === "Review"')
    expect(source).toContain("openDiffReview()")
    expect(source).toContain('selectedKind === "diff" && action === "Challenge"')
    expect(source).toContain('void sendWilliamTurn("Challenge the exact current patch for the selected file.", context)')
    expect(source).toContain('selectedKind === "file" && action === "Ask"')
    expect(source).toContain('kind: "file-ask"')
    expect(source).toContain("fileAskLineContextIsCurrent")
    expect(source).toContain('Exact saved file · ${lineContext.path} · ${lineContext.projectIdentity} · read-only')
    expect(source).toContain('The exact saved file selection changed before William dispatch')
    expect(source).toContain('intent: "improve-diff"')
    expect(source).toContain("expectedDiffFingerprint")
    expect(source).toContain('Improve current change · ${change.path ?? "no file selected"}')
    expect(source).toContain('selectedAgent && agentSessions.pausableSessionIds.includes(selectedAgent.id) ? "Pause" : "Pause unavailable"')
    expect(source).toContain('selectedAgent?.truth === "live" && selectedAgent.providerLabel === "Claude" && selectedAgent.role === "Builder"')
    expect(source).toContain('selectedAgent.mode === "delegate"')
    expect(source).toContain('agentSessions.activeSessionIds.length === 0 ? "Fork" : "Fork unavailable"')
    expect(source).toContain("agentSessions.activeSessionIds.length > 0")
    expect(source).toContain('selectedAgent?.kind === "world-worker" ? ["Inspect", "Ask William", "Council"] as const')
    expect(source).not.toContain('selectedAgent.role === "HERMES" && action === "Inspect"')
    expect(source).not.toContain('selectedAgent.role === "HERMES" && action === "Ask William"')
    expect(source).toContain("materializeExecutionAssignment(selectedAgent.id)")
    expect(source).toContain("encodeExecutionAssignmentInspectorPayload(session, spine)")
    expect(source).toContain("const timer = setInterval(() => void readExecution(), 4000)")
    expect(source).toContain("readId !== latestRead")
    expect(source).toContain("live.workOrderId !== executionWorkOrderId")
    expect(source).toContain('["Inspect", "Ask William", "Talk", "Redirect", "Council", pauseAction, forkAction, selectedAgent?.target ? "Review work" : "Review work unavailable"] as const')
    expect(source).toContain('action === "Review unavailable" || action === "Challenge unavailable" || action === "Explain unavailable" || action === "Pause unavailable"')
    expect(source).toContain('No durable session exists in this Space; use Delegate.')
    expect(source).toContain('action === "Pause unavailable"')
    expect(source).toContain('action === "Pause unavailable" ? "Only the selected running session can be paused."')
    expect(source).toContain('action === "Fork unavailable"')
    expect(source).toContain('lineMode === "fork" ? "Fork session"')
    expect(source).toContain("agentSessions.forkClaudeSession")
    expect(source).toContain('["Summarize", continueAction, spaceDelegateUnavailableReason ? "Delegate unavailable" : "Delegate", "Council"] as const')
    expect(source).toContain("SPACE_CONTINUE_PROMPT")
    expect(source).toContain("setAutomaticSpaceContinuePending(true)")
    expect(source).toContain("void submitLine(null, SPACE_CONTINUE_PROMPT)")
    expect(source).toContain('aria-label="Stop Space continuation"')
    expect(source).toContain('delegateContext.objectBinding.revision === stateRef.current.revision')
    expect(source).toContain('lineSessionCollectionFingerprint(agentSavedSessionsRef.current) === delegateContext.collectionFingerprint')
    expect(source).toContain('if (!spaceContinueContextIsCurrent()) agentSessions.stop(delegateContext.sessionKey)')
    expect(source).toContain('automaticSpaceContinueBaselineTurnIdsRef.current.has(turn.id)')
    expect(source).toContain('agentSessions.stop(automaticSpaceContinueOperationIdRef.current)')
    expect(source).toContain('rawSpaceContinueCandidate.provider === "Local"')
    expect(source).toContain('rawSpaceContinueCandidate.provider === "Claude"')
    expect(source).toContain('rawSpaceContinueCandidate.role === "Reviewer"')
    expect(source).toContain('rawSpaceContinueCandidate.role === "Preview debugger"')
    expect(source).toContain('const nonReadOnlySpaceContinue = Boolean(rawSpaceContinueCandidate && !readOnlySpaceContinue)')
    expect(source).toContain('mutation-capable or not verifiably read-only')
    expect(source).toContain("Selected ${selectedKind}: ${selectedLabel}")
    expect(source).toContain('space.activeWindowId === "running-app" ? "preview"')
    expect(source).toContain('space.activeWindowId === "diff" ? "diff"')
    expect(source).toContain('const councilRequest = lineTarget === "william"')
    expect(source).toContain("void summonCouncil")
  })

  it("projects only real durable sessions and routes delegation into a live agent turn", () => {
    const source = shell()
    expect(source).toContain("useExperienceAgentSessions")
    expect(source).toContain("AgentSessionStrip")
    expect(source).toContain("runAgentTurn")
    expect(source).toContain("onPresentation")
    expect(source).toContain("transitionEpochRef.current === presentationTransitionEpoch")
    expect(source).toContain("worldRef.current === presentationWorldId")
    expect(source).toContain("agentPresentationEpochRef.current === presentationEpoch")
    expect(source).toContain('aria-label="Choose agent provider"')
    expect(source).toContain('provider: "Codex"')
    expect(source).toContain('provider: "Claude"')
    expect(source).toContain('delegateContext.provider === "Codex" && delegateContext.kind === "file"')
    expect(source).not.toContain("const referenceAgents")
    expect(source).not.toContain("reference session")
  })

  it("keeps Local model use conversation-only and outside Delegate, Change, and Review", () => {
    const source = shell()
    expect(source).toContain("Ask Local")
    expect(source).toContain('role: "Thinker"')
    expect(source).toContain('assignment: "Conversation"')
    expect(source).toContain("Local conversation · no workspace mutation")
    expect(source).toContain('delegateContext?.provider === "Local" ? "Ask the Local model"')
    const providerChooser = source.slice(source.indexOf('aria-label="Choose agent provider"'), source.indexOf("</div> : null", source.indexOf('aria-label="Choose agent provider"')))
    expect(providerChooser).toContain("Codex")
    expect(providerChooser).toContain("Claude")
    expect(providerChooser).not.toContain('provider: "Local"')
  })

  it("keeps William's judgment visible and actionable", () => {
    const source = shell()
    const rail = read("components/workspace-shell/william-conversation-rail.tsx")
    expect(source).toContain("williamJudgment")
    expect(source).toContain("/api/environment/judgment")
    expect(source).toContain("payload.judgment")
    expect(source).toContain("await persistBarrierRef.current()")
    expect(source).toContain("judgmentContextKey")
    expect(source).toContain("setJudgment(null)")
    expect(source).toContain("WilliamConversationRail")
    expect(rail).toContain('aria-label="William conversation"')
    expect(rail).toContain('aria-label="William judgment"')
    expect(rail).toContain("Think again")
    expect(rail).toContain("Ask Council")
  })

  it("keeps Council advisory and Mission Control spatial", () => {
    const source = shell()
    expect(source).toContain("BrainCouncilSurface")
    expect(source).toContain("/api/environment/council")
    expect(source).not.toContain("REFERENCE_COUNCIL_SESSION")
    expect(source).toContain('selectedAgent?.kind === "durable-session"')
    expect(source).toContain('selectedAgent?.kind === "durable-session" && action === "Inspect"')
    expect(source).toContain("encodeAgentSessionInspectorPayload(sessionKey, descriptor, projection.truth, new Date().toISOString())")
    expect(source).toContain('providerLabel === "Local" ? ["Inspect", "Ask William", "Talk", "Council"')
    expect(source).toContain('selectedAgent?.kind === "durable-session" && action === "Ask William"')
    expect(source).toContain("durableLineSnapshot(sessionKey, descriptor, new Date().toISOString())")
    expect(source).toContain("The selected browser-saved session changed before William dispatch")
    expect(source).toContain("Browser-saved session snapshot · ${lineContext.sessionKey} · runtime liveness unverified")
    expect(source).toContain('councilSelectedContext.kind === "agent-snapshot"')
    expect(source).toContain("durableCouncilSnapshot(selectedAgent.id, selectedDurableDescriptor")
    expect(source).toContain("CouncilHistoryBrowser")
    expect(source).toContain("openCouncilHistory")
    expect(source).toContain("setCouncilHistorical(true)")
    expect(source).toContain('onNew={() => void summonCouncil(`Challenge the current direction for ${selectedLabel}.`)}')
    const historyOpen = source.slice(source.indexOf("async function openCouncilHistory"), source.indexOf("async function submitLine"))
    expect(historyOpen).toContain('cache: "no-store"')
    expect(historyOpen).not.toContain("summonCouncil(")
    expect(historyOpen).not.toContain("setSpace(")
    expect(source).toContain("MissionControlSurface")
    expect(source).toContain('truth: "live"')
    expect(source).not.toContain('truth: "fixture"')
    expect(source).not.toContain("Illustrative Space · not live runtime state")
    expect(source).toContain("spaceSummaries.map")
  })

  it("connects the Tests, Changes, and Terminal windows to real workspace operations", () => {
    const source = shell()
    expect(source).toContain("DeveloperToolsSurface")
    expect(source).not.toContain("Reference surface · no live adapter attached")
    expect(source).not.toContain("project runtime not attached")
  })

  it("uses the restrained matte charcoal and sage product language", () => {
    const css = spatialCss().toLowerCase()
    expect(css).toContain("#090c09")
    expect(css).toContain("#8eb181")
    expect(css).toContain(".williamrail")
    expect(css).not.toContain("#b8794e")
    expect(css).not.toContain("#cc8d61")
  })

  it("keeps TerraFusion inside a neutral developer preview, never WilliamOS business UI", () => {
    const source = shell().toLowerCase()
    expect(source).toContain("developer preview")
    expect(source).toContain("running terrafusion application")
    expect(source).toContain("developer preview unavailable")
    expect(source).not.toContain("parcel")
    expect(source).not.toContain("appeal")
    expect(source).not.toContain("taxpayer")
    expect(source).not.toContain("pacs")
  })
})
