import path from "node:path"
import { promises as fs } from "node:fs"
import { NextResponse } from "next/server"

export const runtime = "nodejs"

type SetupPayload = {
  databaseUrl?: unknown
  authSecret?: unknown
  authUrl?: unknown
}

function localSetupEnabled() {
  if (process.env.LOCAL_SETUP_ENABLED === "false") return false
  return process.env.NODE_ENV !== "production"
}

function isLoopbackHost(url: URL) {
  return url.hostname === "localhost" || url.hostname === "127.0.0.1" || url.hostname === "::1"
}

function asTrimmedString(value: unknown) {
  return typeof value === "string" ? value.trim() : ""
}

function validatePayload(payload: SetupPayload) {
  const databaseUrl = asTrimmedString(payload.databaseUrl)
  const authSecret = asTrimmedString(payload.authSecret)
  const authUrl = asTrimmedString(payload.authUrl)

  if (!databaseUrl) {
    throw new Error("DATABASE_URL is required.")
  }
  if (!authSecret) {
    throw new Error("BETTER_AUTH_SECRET is required.")
  }
  if (authSecret.length < 32) {
    throw new Error("BETTER_AUTH_SECRET must be at least 32 characters.")
  }
  if (!authUrl) {
    throw new Error("BETTER_AUTH_URL is required.")
  }

  try {
    new URL(authUrl)
  } catch {
    throw new Error("BETTER_AUTH_URL must be a valid URL.")
  }

  return { databaseUrl, authSecret, authUrl }
}

function envLine(key: string, value: string) {
  return `${key}=${JSON.stringify(value)}`
}

async function writeLocalEnv(input: {
  databaseUrl: string
  authSecret: string
  authUrl: string
}) {
  const envPath = path.join(process.cwd(), ".env.local")
  const lines = [
    "# Generated by /setup local onboarding assistant",
    envLine("DATABASE_URL", input.databaseUrl),
    envLine("BETTER_AUTH_SECRET", input.authSecret),
    envLine("BETTER_AUTH_URL", input.authUrl),
    envLine("LOCAL_SETUP_ENABLED", "true"),
    ...(process.env.GROQ_API_KEY
      ? [envLine("GROQ_API_KEY", process.env.GROQ_API_KEY)]
      : []),
  ]

  await fs.writeFile(envPath, `${lines.join("\n")}\n`, "utf8")
}

export async function POST(req: Request) {
  if (!localSetupEnabled()) {
    return NextResponse.json(
      {
        ok: false,
        message:
          "Local setup assistant is disabled in this environment. Contact your platform administrator.",
      },
      { status: 403 },
    )
  }

  const url = new URL(req.url)
  if (!isLoopbackHost(url)) {
    return NextResponse.json(
      {
        ok: false,
        message:
          "Local setup assistant only accepts loopback requests. Use localhost when running setup.",
      },
      { status: 403 },
    )
  }

  if ((process.env.AUTH_SIGNUP_MODE ?? "bootstrap") === "closed") {
    return NextResponse.json(
      {
        ok: false,
        message:
          "Local setup assistant is disabled because AUTH_SIGNUP_MODE=closed.",
      },
      { status: 403 },
    )
  }

  let payload: SetupPayload
  try {
    payload = (await req.json()) as SetupPayload
  } catch {
    return NextResponse.json(
      { ok: false, message: "Invalid JSON payload." },
      { status: 400 },
    )
  }

  let validated: { databaseUrl: string; authSecret: string; authUrl: string }
  try {
    validated = validatePayload(payload)
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        message: error instanceof Error ? error.message : "Invalid setup payload.",
      },
      { status: 400 },
    )
  }

  try {
    await writeLocalEnv(validated)
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        message:
          error instanceof Error
            ? `Failed to write .env.local: ${error.message}`
            : "Failed to write .env.local",
      },
      { status: 500 },
    )
  }

  return NextResponse.json({
    ok: true,
    message:
      "Saved setup to .env.local. Restart the app process to apply the new environment variables.",
    restartRequired: true,
  })
}
