import path from "node:path"

import { applicationReply, resolveApplicationRouteContext, type ApplicationRouteContext } from "./application-route-context"
import { resolveApplicationProposalRuntimeRoot } from "./proposal-runtime-root.mjs"

export type ApplicationProposalRouteContext = ApplicationRouteContext & Readonly<{ runtimeRoot: string }>

const ALLOWED_CODES = new Set([
  "APPLICATION_CEREBRAS_EXECUTION_FAILED",
  "APPLICATION_CEREBRAS_REQUEST_INVALID",
  "APPLICATION_CEREBRAS_RESPONSE_INVALID",
  "APPLICATION_CEREBRAS_TIMEOUT",
  "APPLICATION_CEREBRAS_UNAVAILABLE",
  "APPLICATION_EXECUTION_ROUTE_INVALID",
  "APPLICATION_EXECUTION_ROUTE_UNAVAILABLE",
  "APPLICATION_EXTERNAL_EGRESS_APPROVAL_REQUIRED",
  "APPLICATION_PROPOSAL_ARTIFACT_CLEANUP_FAILED",
  "APPLICATION_PROPOSAL_BASE_INVALID",
  "APPLICATION_PROPOSAL_CANONICAL_DIRTY",
  "APPLICATION_PROPOSAL_COMMAND_FAILED",
  "APPLICATION_PROPOSAL_COMMIT_INVALID",
  "APPLICATION_PROPOSAL_CREATION_RECOVERY_UNCERTAIN",
  "APPLICATION_PROPOSAL_DIFF_INVALID",
  "APPLICATION_PROPOSAL_IGNORED_PATH_REFUSED",
  "APPLICATION_PROPOSAL_LOCK_UNCERTAIN",
  "APPLICATION_PROPOSAL_LISTING_UNCERTAIN",
  "APPLICATION_PROPOSAL_MANIFEST_DRIFT",
  "APPLICATION_PROPOSAL_NO_CHANGE",
  "APPLICATION_PROPOSAL_NOT_APPLICABLE",
  "APPLICATION_PROPOSAL_NOT_FOUND",
  "APPLICATION_PROPOSAL_OWNER_MISMATCH",
  "APPLICATION_PROPOSAL_PATCH_INVALID",
  "APPLICATION_PROPOSAL_PATCH_MISMATCH",
  "APPLICATION_PROPOSAL_PATCH_SCOPE_MISMATCH",
  "APPLICATION_PROPOSAL_PATCH_SIZE_REFUSED",
  "APPLICATION_PROPOSAL_PATH_REFUSED",
  "APPLICATION_PROPOSAL_POLICY_INVALID",
  "APPLICATION_PROPOSAL_QUARANTINED",
  "APPLICATION_PROPOSAL_RECEIPT_INVALID",
  "APPLICATION_PROPOSAL_REJECTION_INVALID",
  "APPLICATION_PROPOSAL_RENAME_REFUSED",
  "APPLICATION_PROPOSAL_REPOSITORY_BUSY",
  "APPLICATION_PROPOSAL_REPOSITORY_INVALID",
  "APPLICATION_PROPOSAL_REQUEST_INVALID",
  "APPLICATION_PROPOSAL_RESIDENT_EVIDENCE_INVALID",
  "APPLICATION_PROPOSAL_RESIDENT_HEAD_MUTATED",
  "APPLICATION_PROPOSAL_RESIDENT_UNAVAILABLE",
  "APPLICATION_PROPOSAL_ROLLBACK_FAILED",
  "APPLICATION_PROPOSAL_RUNTIME_ROOT_INVALID",
  "APPLICATION_PROPOSAL_SECRET_DETECTED",
  "APPLICATION_PROPOSAL_SOURCE_SIZE_REFUSED",
  "APPLICATION_PROPOSAL_STALE_BASE",
  "APPLICATION_PROPOSAL_TARGET_DIRTY",
  "APPLICATION_PROPOSAL_VALIDATION_FAILED",
  "APPLICATION_PROPOSAL_VALIDATION_HASH_MISMATCH",
  "APPLICATION_PROPOSAL_WORKSPACE_FILE_INVALID",
  "APPLICATION_PROPOSAL_WORKTREE_CLEANUP_FAILED",
  "APPLICATION_PROPOSAL_WORKTREE_INVALID",
  "CEREBRAS_APPLICATION_CHANGE_FAILED",
  "CEREBRAS_APPLICATION_INPUT_INVALID",
  "CEREBRAS_APPLICATION_MODEL_MISMATCH",
  "CEREBRAS_APPLICATION_RESPONSE_INVALID",
  "CEREBRAS_APPLICATION_SECRET_DETECTED",
  "EXTERNAL_API_AUTH_FAILURE",
  "EXTERNAL_API_COST_EVIDENCE_MISSING",
  "EXTERNAL_API_INCOMPLETE_RESPONSE",
  "EXTERNAL_API_INSUFFICIENT_CREDIT",
  "EXTERNAL_API_KEY_MISSING",
  "EXTERNAL_API_MALFORMED_RESPONSE",
  "EXTERNAL_API_OUTAGE",
  "EXTERNAL_API_RATE_LIMIT",
  "EXTERNAL_API_TIMEOUT",
  "EXTERNAL_API_UNSUPPORTED_CAPABILITY",
  "EXTERNAL_EGRESS_REFUSED",
  "SPEND_CAP_EXCEEDS_CEILING",
])

export async function resolveApplicationProposalRouteContext(projectKey: unknown): Promise<
  Readonly<{ ok: true; context: ApplicationProposalRouteContext }> | Readonly<{ ok: false; response: Response }>
> {
  const resolved = await resolveApplicationRouteContext(projectKey)
  if (!resolved.ok) return resolved
  const configured = process.env.WILLIAMOS_APPLICATION_RUNTIME_ROOT?.trim()
  if (!configured || !path.isAbsolute(configured) || configured.includes("\0")) {
    return { ok: false, response: applicationReply({ error: "APPLICATION_RUNTIME_ROOT_NOT_CONFIGURED" }, 503) }
  }
  try {
    const runtimeRoot = resolveApplicationProposalRuntimeRoot(path.resolve(configured), resolved.context.application.repositoryRoot)
    return { ok: true, context: { ...resolved.context, runtimeRoot } }
  } catch {
    return { ok: false, response: applicationReply({ error: "APPLICATION_RUNTIME_ROOT_INVALID" }, 503) }
  }
}

export function applicationProposalErrorCode(error: unknown): string {
  if (!(error instanceof Error)) return "APPLICATION_PROPOSAL_UNAVAILABLE"
  const code = error.message.split(":", 1)[0]
  return ALLOWED_CODES.has(code) ? code : "APPLICATION_PROPOSAL_UNAVAILABLE"
}

export function applicationProposalError(error: unknown): Response {
  const code = applicationProposalErrorCode(error)
  const status = code === "APPLICATION_PROPOSAL_NOT_FOUND" ? 404
    : ["APPLICATION_PROPOSAL_REQUEST_INVALID", "APPLICATION_PROPOSAL_REJECTION_INVALID", "APPLICATION_EXECUTION_ROUTE_INVALID"].includes(code) ? 400
      : code === "APPLICATION_PROPOSAL_OWNER_MISMATCH" ? 403
        : /(?:STALE|DIRTY|NOT_APPLICABLE|REPOSITORY_BUSY|QUARANTINED)/.test(code) ? 409
          : /(?:PATH_|IGNORED_|PATCH_SIZE|PATCH_SCOPE|RENAME_|NO_CHANGE|VALIDATION_|SECRET_DETECTED|MANIFEST_DRIFT)/.test(code) ? 422
            : 503
  return applicationReply({ error: code }, status)
}
