Match User williamos-fabric
    AuthorizedKeysFile /etc/ssh/authorized_keys/williamos-fabric /etc/ssh/authorized_keys/williamos-fabric-standing-hash
    AuthorizedKeysCommand none
    AuthorizedPrincipalsCommand none
    TrustedUserCAKeys none
    HostbasedAuthentication no
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthenticationMethods publickey
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PermitTTY no
    PermitTunnel no
    GatewayPorts no
    PermitUserRC no
