import {createHash,createPrivateKey,createPublicKey,sign as edSign,verify as edVerify,type KeyObject} from 'node:crypto'
export type Digest=`sha256:${string}`
export type WorkerMessageKind='PULL'|'HEARTBEAT'|'CANCEL'|'CANCEL_ACK'
export interface WorkerBinding{jobId:string;claimId:string;attemptId:string;leaseId:string;effectDomain:string;idempotencyKey:string;workerId:string;instanceId:string;bootId:string;fencingToken:string;renewalSequence:string;authorityDigest:Digest;capabilityDigest:Digest;inputDigest:Digest;baseDigest:Digest;policyDigest:Digest;requestedOutputDigest:Digest;configDigest:Digest;imageDigest:Digest;modelDigest:Digest}
export interface SignedWorkerEnvelope{protocolVersion:'aeh.worker.v1';kind:WorkerMessageKind;algorithm:'Ed25519';keyId:string;messageId:string;operationId:string;nonce:string;issuedAt:string;notBefore:string;expiresAt:string;binding:WorkerBinding;payloadDigest:Digest;payloadBytes:number;signature:string}
export interface WorkerKeyRecord{keyId:string;algorithm:'Ed25519';state:'ACTIVE'|'RETIRING'|'REVOKED';notBefore:string;notAfter:string;publicKey:KeyObject|string}
export interface WorkerSigningKeyRecord{keyId:string;algorithm:'Ed25519';state:'ACTIVE';notBefore:string;notAfter:string;privateKey:KeyObject|string}
export class WorkerProtocolError extends Error{readonly code:string;constructor(code:string){super(code);this.code=code;this.name='WorkerProtocolError'}}
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i,DIGEST=/^sha256:[a-f0-9]{64}$/,TOKEN=/^[A-Za-z0-9._:-]{1,128}$/,B64URL=/^[A-Za-z0-9_-]{86}$/
const ENVELOPE_KEYS=['algorithm','binding','expiresAt','issuedAt','keyId','kind','messageId','nonce','notBefore','operationId','payloadBytes','payloadDigest','protocolVersion','signature']
const BINDING_KEYS=['attemptId','authorityDigest','baseDigest','bootId','capabilityDigest','claimId','configDigest','effectDomain','fencingToken','idempotencyKey','imageDigest','inputDigest','instanceId','jobId','leaseId','modelDigest','policyDigest','renewalSequence','requestedOutputDigest','workerId']
export const MAX_PAYLOAD_BYTES=1_048_576,MAX_OUTPUT_BYTES=4_194_304,MAX_ENVELOPE_TTL_MS=300_000,MAX_CLOCK_SKEW_MS=30_000
export const MAX_OUTPUT_TOKENS=131_072,MAX_RUNTIME_MS=3_600_000,MAX_ARTIFACTS=128
export interface WorkerOutputArtifact{outputDigest:Digest;outputBytes:number;outputTokens:number;runtimeMs:number;artifactDigests:readonly Digest[];truncated:boolean}
export function validateOutputArtifact(a:WorkerOutputArtifact,bytes:Uint8Array){if(!DIGEST.test(a.outputDigest)||digestBytes(bytes)!==a.outputDigest)throw new WorkerProtocolError('WORKER_OUTPUT_DIGEST_INVALID');if(!Number.isSafeInteger(a.outputBytes)||a.outputBytes!==bytes.byteLength||a.outputBytes>MAX_OUTPUT_BYTES||!Number.isSafeInteger(a.outputTokens)||a.outputTokens<0||a.outputTokens>MAX_OUTPUT_TOKENS||!Number.isSafeInteger(a.runtimeMs)||a.runtimeMs<0||a.runtimeMs>MAX_RUNTIME_MS||a.artifactDigests.length>MAX_ARTIFACTS||a.artifactDigests.some(x=>!DIGEST.test(x))||typeof a.truncated!=='boolean')throw new WorkerProtocolError('WORKER_OUTPUT_BOUNDS_INVALID');return Object.freeze(a)}
function strictKeys(v:Record<string,unknown>,keys:string[],code:string){if(Object.keys(v).sort().join('\0')!==[...keys].sort().join('\0'))throw new WorkerProtocolError(code)}
function normalizeString(v:string){if(v!==v.normalize('NFC'))throw new WorkerProtocolError('WORKER_CANONICAL_UNICODE_INVALID');return v}
export function canonicalizeJcs(value:unknown):string{if(value===null)return'null';if(typeof value==='string')return JSON.stringify(normalizeString(value));if(typeof value==='boolean')return String(value);if(typeof value==='number'){if(!Number.isSafeInteger(value))throw new WorkerProtocolError('WORKER_CANONICAL_NUMBER_INVALID');return String(value)}if(Array.isArray(value))return`[${value.map(canonicalizeJcs).join(',')}]`;if(typeof value==='object'){const o=value as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(normalizeString(k))}:${canonicalizeJcs(o[k])}`).join(',')}}`}throw new WorkerProtocolError('WORKER_CANONICAL_TYPE_INVALID')}
function unsigned(e:SignedWorkerEnvelope){const{signature,...rest}=e;return rest}
export function canonicalEnvelope(e:SignedWorkerEnvelope){return Buffer.from(canonicalizeJcs(unsigned(e)),'utf8')}
export function envelopeReceiptDigest(e:SignedWorkerEnvelope):Digest{return`sha256:${createHash('sha256').update(canonicalizeJcs(e),'utf8').digest('hex')}`}
export function digestBytes(value:Uint8Array):Digest{return`sha256:${createHash('sha256').update(value).digest('hex')}`}
function instant(v:string,code:string){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v))throw new WorkerProtocolError(code);const n=Date.parse(v);if(!Number.isFinite(n))throw new WorkerProtocolError(code);return n}
export function validateEnvelopeShape(e:SignedWorkerEnvelope,payload:Uint8Array,nowMs=Date.now()){
 strictKeys(e as unknown as Record<string,unknown>,ENVELOPE_KEYS,'WORKER_ENVELOPE_FIELDS_INVALID');strictKeys(e.binding as unknown as Record<string,unknown>,BINDING_KEYS,'WORKER_BINDING_FIELDS_INVALID')
 if(e.protocolVersion!=='aeh.worker.v1'||e.algorithm!=='Ed25519'||!['PULL','HEARTBEAT','CANCEL','CANCEL_ACK'].includes(e.kind))throw new WorkerProtocolError('WORKER_ENVELOPE_VERSION_INVALID')
 for(const v of [e.messageId,e.operationId,e.binding.jobId,e.binding.claimId,e.binding.attemptId,e.binding.leaseId,e.binding.workerId,e.binding.instanceId,e.binding.bootId])if(!UUID.test(v))throw new WorkerProtocolError('WORKER_ENVELOPE_ID_INVALID')
 for(const v of [e.binding.authorityDigest,e.binding.capabilityDigest,e.binding.inputDigest,e.binding.baseDigest,e.binding.policyDigest,e.binding.requestedOutputDigest,e.binding.configDigest,e.binding.imageDigest,e.binding.modelDigest,e.payloadDigest])if(!DIGEST.test(v))throw new WorkerProtocolError('WORKER_ENVELOPE_DIGEST_INVALID')
 for(const v of [e.keyId,e.nonce,e.binding.effectDomain,e.binding.idempotencyKey])if(!TOKEN.test(v))throw new WorkerProtocolError('WORKER_ENVELOPE_TOKEN_INVALID')
 if(!/^\d+$/.test(e.binding.fencingToken)||BigInt(e.binding.fencingToken)<=0n||!/^\d+$/.test(e.binding.renewalSequence))throw new WorkerProtocolError('WORKER_FENCE_INVALID')
 if(!Number.isSafeInteger(e.payloadBytes)||e.payloadBytes!==payload.byteLength||payload.byteLength>MAX_PAYLOAD_BYTES)throw new WorkerProtocolError('WORKER_PAYLOAD_OVERSIZE');if(digestBytes(payload)!==e.payloadDigest)throw new WorkerProtocolError('WORKER_PAYLOAD_FORGED')
 const issued=instant(e.issuedAt,'WORKER_TIME_INVALID'),nbf=instant(e.notBefore,'WORKER_TIME_INVALID'),exp=instant(e.expiresAt,'WORKER_TIME_INVALID');if(nbf<issued-MAX_CLOCK_SKEW_MS||exp<=nbf||exp-issued>MAX_ENVELOPE_TTL_MS||issued>nowMs+MAX_CLOCK_SKEW_MS||nbf>nowMs+MAX_CLOCK_SKEW_MS||exp<=nowMs)throw new WorkerProtocolError('WORKER_ENVELOPE_EXPIRED');if(!B64URL.test(e.signature))throw new WorkerProtocolError('WORKER_SIGNATURE_FORMAT_INVALID')
}
export class WorkerKeyring{private readonly keys=new Map<string,WorkerKeyRecord>();constructor(records:readonly WorkerKeyRecord[]){for(const r of records){if(this.keys.has(r.keyId)||!TOKEN.test(r.keyId)||r.algorithm!=='Ed25519')throw new WorkerProtocolError('WORKER_KEY_INVALID');this.keys.set(r.keyId,Object.freeze({...r}))}}
 verify(e:SignedWorkerEnvelope,atMs:number){const k=this.keys.get(e.keyId);if(!k||k.state==='REVOKED')throw new WorkerProtocolError('WORKER_KEY_REVOKED');const from=instant(k.notBefore,'WORKER_KEY_INVALID'),to=instant(k.notAfter,'WORKER_KEY_INVALID');if(atMs<from||atMs>=to)throw new WorkerProtocolError('WORKER_KEY_NOT_VALID');const key=typeof k.publicKey==='string'?createPublicKey(k.publicKey):k.publicKey;if(!edVerify(null,canonicalEnvelope(e),key,Buffer.from(e.signature,'base64url')))throw new WorkerProtocolError('WORKER_SIGNATURE_INVALID')}
}
export function signEnvelope(e:Omit<SignedWorkerEnvelope,'signature'>,record:WorkerSigningKeyRecord,nowMs=Date.now()):SignedWorkerEnvelope{if(e.algorithm!=='Ed25519'||record.algorithm!=='Ed25519'||record.state!=='ACTIVE'||record.keyId!==e.keyId||nowMs<instant(record.notBefore,'WORKER_KEY_INVALID')||nowMs>=instant(record.notAfter,'WORKER_KEY_INVALID'))throw new WorkerProtocolError('WORKER_KEY_NOT_ACTIVE');const provisional={...e,signature:'A'.repeat(86)} as SignedWorkerEnvelope;const key=typeof record.privateKey==='string'?createPrivateKey(record.privateKey):record.privateKey;const signature=edSign(null,canonicalEnvelope(provisional),key).toString('base64url');return Object.freeze({...e,signature})}
export function verifyPullEnvelope(e:SignedWorkerEnvelope,payload:Uint8Array,keyring:WorkerKeyring,now=new Date()){validateEnvelopeShape(e,payload,now.getTime());keyring.verify(e,now.getTime());return Object.freeze(e)}
