import type{QueryExecutor}from'./claim-lease-engine'
import{canonicalizeJcs,envelopeReceiptDigest,verifyPullEnvelope,WorkerKeyring,type SignedWorkerEnvelope,type WorkerBinding}from'./worker-protocol'
function verifiedPayload<T extends Record<string,unknown>>(e:SignedWorkerEnvelope,payload:Uint8Array,keyring:WorkerKeyring,kind:SignedWorkerEnvelope['kind'],keys:readonly string[]):T{verifyPullEnvelope(e,payload,keyring);if(e.kind!==kind)throw new Error('WORKER_MESSAGE_KIND_INVALID');let v:unknown;try{v=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(payload))}catch{throw new Error('WORKER_PAYLOAD_JSON_INVALID')}if(!v||Array.isArray(v)||typeof v!=='object'||Object.keys(v).sort().join('\0')!==[...keys].sort().join('\0')||Buffer.from(canonicalizeJcs(v)).compare(Buffer.from(payload))!==0)throw new Error('WORKER_PAYLOAD_SCHEMA_INVALID');return v as T}
export async function pullForWorker(executor:QueryExecutor,e:SignedWorkerEnvelope,payload:Uint8Array,keyring:WorkerKeyring){const p=verifiedPayload<{ttlSeconds:number}>(e,payload,keyring,'PULL',['ttlSeconds']),b=e.binding;return(await executor.query("SELECT * FROM ai_evalops.pull_worker_envelope($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,make_interval(secs=>$11),$12,$13)",[e.messageId,envelopeReceiptDigest(e),e.keyId,b.effectDomain,b.workerId,b.instanceId,b.bootId,b.claimId,b.leaseId,e.operationId,p.ttlSeconds,b.authorityDigest,e.expiresAt])).rows[0]}
export async function heartbeat(executor:QueryExecutor,e:SignedWorkerEnvelope,payload:Uint8Array,keyring:WorkerKeyring){const p=verifiedPayload<{ttlSeconds:number}>(e,payload,keyring,'HEARTBEAT',['ttlSeconds']),b=e.binding;const receipt=(await executor.query<{renewal_sequence:string;expires_at:string}>("SELECT * FROM ai_evalops.worker_heartbeat($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,make_interval(secs=>$13),$14,$15,$16)",[e.messageId,envelopeReceiptDigest(e),e.keyId,b.effectDomain,b.leaseId,b.attemptId,b.workerId,b.instanceId,b.bootId,b.fencingToken,b.renewalSequence,e.operationId,p.ttlSeconds,b.authorityDigest,b.capabilityDigest,e.expiresAt])).rows[0];if(!receipt||BigInt(receipt.renewal_sequence)!==BigInt(b.renewalSequence)+1n)throw new Error('WORKER_HEARTBEAT_RECEIPT_INVALID');return Object.freeze(receipt)}
type CancelPayload={cancellationId:string;jobId:string;expectedProjectionVersion:string;reason:string;actorId:string;ttlSeconds:number}
export async function requestCancellation(executor:QueryExecutor,e:SignedWorkerEnvelope,payload:Uint8Array,keyring:WorkerKeyring){const p=verifiedPayload<CancelPayload>(e,payload,keyring,'CANCEL',['actorId','cancellationId','expectedProjectionVersion','jobId','reason','ttlSeconds']),b=e.binding;return(await executor.query("SELECT * FROM ai_evalops.request_worker_cancellation_enveloped($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,make_interval(secs=>$15),$16,$17,$18)",[e.messageId,envelopeReceiptDigest(e),e.keyId,b.effectDomain,e.expiresAt,p.cancellationId,e.operationId,p.jobId,b.attemptId,b.fencingToken,p.expectedProjectionVersion,p.reason,p.actorId,b.authorityDigest,p.ttlSeconds,b.workerId,b.instanceId,b.bootId])).rows[0]}
type AckPayload={acknowledgementId:string;cancellationId:string;disposition:'STOPPED_BEFORE_EFFECT'|'STOPPED_AFTER_EFFECT_STARTED'|'STOP_STATUS_AMBIGUOUS';observationEvidenceId:string;observationEvidenceDigest:`sha256:${string}`}
export async function acknowledgeCancellation(executor:QueryExecutor,e:SignedWorkerEnvelope,payload:Uint8Array,keyring:WorkerKeyring){const p=verifiedPayload<AckPayload>(e,payload,keyring,'CANCEL_ACK',['acknowledgementId','cancellationId','disposition','observationEvidenceDigest','observationEvidenceId']),b=e.binding;return(await executor.query("SELECT * FROM ai_evalops.acknowledge_worker_cancellation_enveloped($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)",[e.messageId,envelopeReceiptDigest(e),e.keyId,b.effectDomain,b.authorityDigest,e.expiresAt,p.acknowledgementId,e.operationId,p.cancellationId,b.workerId,b.instanceId,b.bootId,b.fencingToken,b.renewalSequence,p.disposition,p.observationEvidenceId,p.observationEvidenceDigest])).rows[0]}
export interface WorkerAdapter{prepare(envelope:SignedWorkerEnvelope):Promise<void>;start(binding:WorkerBinding):Promise<void>;observe(binding:WorkerBinding):Promise<Readonly<{state:string}>>;cancel(binding:WorkerBinding,reason:string):Promise<'STOPPED_BEFORE_EFFECT'|'STOPPED_AFTER_EFFECT_STARTED'|'STOP_STATUS_AMBIGUOUS'>;collect(binding:WorkerBinding):Promise<Uint8Array>}
export function assertWorkerAdapter(value:unknown):asserts value is WorkerAdapter{for(const method of['prepare','start','observe','cancel','collect'])if(typeof(value as Record<string,unknown>)?.[method]!=='function')throw new Error('WORKER_ADAPTER_NONCONFORMANT')}
// Settlement is intentionally absent: WO017 delivery, WO018 descriptors, and WO019 reconciliation own terminal truth.
